language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.6
    - os: osx
      osx_image: xcode9.3beta
      language: generic

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew update || brew update
      # The following wasn't required in the past and therefore may become
      # obsolete once again in the future. Let's wait and see.
      wget https://bootstrap.pypa.io/get-pip.py
      sudo python get-pip.py
      sudo pip install virtualenv
      virtualenv $HOME
      source $HOME/bin/activate
    else
      sudo apt-get update -qq
    fi

install:
  - pip install -U pip setuptools
  - pip install '.[dev]'
  - python setup.py develop
  - pip install mock pytest pytest-cov codecov coveralls

script:
  - py.test --cov=egghatch

  - python -c 'import egghatch, sys ; assert "capstone" not in sys.modules'

after_success:
  - coveralls
  - codecov
